# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('hmfp', ['core'])
    module.source = [
        'model/hmfp-routing-protocol.cc',
        'model/hmfp-rtable.cc',
        'model/hmfp-header.cc',
        'helper/hmfp-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('hmfp')
    module_test.source = [
        'test/hmfp-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'hmfp'
    headers.source = [
        'model/hmfp-routing-protocol.h',
        'model/hmfp-rtable.h',
        'model/hmfp-header.h',
        'helper/hmfp-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

